### ISSUE TITLE
package name in lowercase

### ISSUE THREAD

**Issue by ghost** [michal-h21/ctanbib#1]
I was wondering if one could also get the package’s name in lowercase?

But `local titleformat = string.lower("%s")` wouldn’t work?!
Any suggestions, @michal-h21 ?

**Comment by michal-h21** [comment]
This makes lowercase the "%s" string, it doesn'ŧ have any effect on the title formtting. You need to make lowercase the output of `get_title` function:

     e.title = unicode.utf8.lower(get_title(record.name))

I used `unicode.utf8.lower` as it supports also accented letters.

**Comment by ghost** [comment]
ok,  but where do I have to insert that line in the function below?
(sorry, my Lua is very very poor)

```
local get_title = function(title)
    local title = title:gsub("^(.)", function(a) return unicode.utf8.upper(a) end)
    return string.format(titleformat, title)
end
```

**Comment by ghost** [comment]
sorry, my fault....

probably here:

`e.title = get_title(record.name)` replace with `e.title = unicode.utf8.lower(get_title(record.name))`
