### ISSUE TITLE
Enntrytype

### ISSUE THREAD

**Issue by hvoss49** [michal-h21/ctanbib#10]
We always get the entry type @manual, whereas we get before @ctan when using the -c or -C option.
With a @ctan output it is much more easier to create a special bibliography output as for @manual,
which is already used in a lot of bib styles in a way which is not really compatible to CTAN documents.

**Comment by michal-h21** [comment]
Yes, you can now get the `@ctan` entry type using the `-e` option:

     ctanbib -e ctan -C biblatex microtype

```
@ctan{biblatex,
title = {The BibLaTeX package},
subtitle = {Sophisticated Bibliographies in LaTeX},
author = {Lehman, Philipp and Kime, Philip},
url = {/macros/latex/contrib/biblatex},
urldate = {2021-07-01}, 
date = {2020-12-31},
version = {3.16},
}

@ctan{microtype,
title = {The Microtype package},
subtitle = {Subliminal refinements towards typographical perfection},
author = {Schlicht, Robert},
url = {/macros/latex/contrib/microtype},
urldate = {2021-07-01}, 
date = {2021-03-14},
version = {2.8c},
}


```

**Comment by hvoss49** [comment]
Ah, thanks. I missed that ...
