### ISSUE TITLE
Output UTF-8 umlauts

### ISSUE THREAD

**Issue by koppor** [michal-h21/ctanbib#11]
The output (at least on Windows 11) seems to use a different encoding than UTF-8:

```cmd
$ ctanbib coverpage
@manual{coverpage,
title = {The coverpage package},
subtitle = {Automatic cover page creation for scientific papers},
author = {Kopp, Oliver and M├╝hlich, Matthias},
url = {https://ctan.org/pkg/coverpage},
urldate = {2023-10-07},
date = {},
version = {1.01},
}
```

Moreover, there should be a hint if the `date` field could not be filled.

**Comment by michal-h21** [comment]
Thanks for the report. It shouldn't be hard to fix the `date` issue, but I am not sure why you get the incorrect text encoding. The XML file we get from CTAN is encoded in UTF-8 and Ctanbib doesn't convert it to anything else. Isn't it possible that Windows terminal converts it automatically? It seems that it thinks that the output is in Latin 1 and converts it to UTF-8.

**Comment by michal-h21** [comment]
@koppor it seems that this is Windows command line issue, it incorrectly supports UTF-8. You can change the codepage that command line uses using `chcp 65001` command. After that, it should display accented letters correctly.

**Comment by koppor** [comment]
Oh, OK, Thank you for the hint. I don't dare to do it. See https://stackoverflow.com/a/388500/873282 for details.

There is also

> To input/output Unicode in a console, one does not need to set the code page.

I will close the issue as the tool outputs UTF-8, but cmd.exe can't handle it.
