### ISSUE TITLE
order of author names switch from time to time

### ISSUE THREAD

**Issue by ghost** [michal-h21/ctanbib#2]
I couldn’t figure out if there is a rule or something, but the names of authors are getting switched each time I create a bib-file.

<img width="717" alt="bildschirmfoto 2018-08-20 um 21 27 41" src="https://user-images.githubusercontent.com/12896078/44362361-1d2e0a00-a4c1-11e8-93e3-af633661a9db.png">

**Comment by michal-h21** [comment]
This issue was caused by the method used for the XML parsing - the LuaXML library provides several parsers. The one I used enables simple retrieving of the fields, but it doesn't keep the order of elements (because they are stored  in a hash table, which doesn't have fixed ordering in Lua).

I rewrote ctanbib to use a different method, using simple DOM object, which doesn't have these issues. I hope it doesn't add more issues :)

**Comment by ghost** [comment]
Ok, Thank you! I will test it.

**Comment by ghost** [comment]
it didn’t work as far as I can tell, furthermore `e.title = unicode.utf8.lower(get_title(record.name))` doesnt work either. 
I hope you do not spend too much time on this – the order of names is not so important I am happy that I can get all information automatically from CTAN.

**Comment by michal-h21** [comment]
What kind of error do you get? Do you use actual TL? I used features which are only in recent versions of LuaXML. It wasn't that much work fortunatelly.

**Comment by ghost** [comment]
With `e.title = unicode.utf8.lower(get_title(record.name))` I get the error `tools/ctanbib.lua:61: attempt to index local 'record' (a nil value)`

**Comment by ghost** [comment]
but even without the change of `e.title` the names still are getting switched

**Comment by michal-h21** [comment]
Sure, use 

      e.title = unicode.utf8.lower(get_title(record)) 

instead.

Regarding the name issue - I've found that the name order is different in the original XML each time it is downloaded, so it isn't something we can fix. Maybe we can sort, so it  stays in the same order.

**Comment by ghost** [comment]
its working fine now, thanks.

strange enough, that the names are getting changed in the XML every time. 
Sorting them would be done alphabetically?! But that might not be the right sorting order since sometimes the names are sorted by another criteria (we dont know?).

**Comment by michal-h21** [comment]
We don't have another criterion than alphabetic sort, unfortunatelly. Maybe sort names without surnames first (these are usually team names, such as "The LaTeX Team".

It is really not that useful in my opinion.

**Comment by ghost** [comment]
you are right. We can leave that aside/unsolved since it has nothing to do with your script. 

btw – do you think of publishing it on CTAN?

**Comment by michal-h21** [comment]
I think it should be fixed on the CTAN side.

I can publish it on CTAN, it just needs some documentation :)

**Comment by ghost** [comment]
you already did some documentation on TeX.SE. :) 
However I think it will be worth it.

**Comment by michal-h21** [comment]
@LukasCBossert I've just uploaded it to CTAN

**Comment by ghost** [comment]
great! Looking forward seeing it online and referencing to it using `ctanbib` :)
