### ISSUE TITLE
code in certain fields

### ISSUE THREAD

**Issue by ghost** [michal-h21/ctanbib#3]
consider this package information

```
@manual{marginnote,
title = {The Marginnote package},
subtitle = {Notes in the margin, even where \marginpar fails},
author = {Kohm, Markus},
url = {https://komascript.de/marginnote},
urldate = {2018-09-09}, 
date = {2018-08-09},
version = {1.4b}
}
```

It is probably not the default of your code, but is there a possibility to mask such code parts (`\marginpar`)? It leads to a strange appearance in the bibliography.

I know I could do that manually but I keep getting the updated list from CTAN every time so it would be overwritten then.

**Comment by michal-h21** [comment]
Sure, what do you think would be the best solution? Remove the commands entirely? Or just remove the `\` character?

**Comment by ghost** [comment]
sorry just the \ or put the command in texttt ?

**Comment by michal-h21** [comment]
The `\texttt` or `\verb` doesn't seem to work. But replacing `\` with `\textbackslash` seems to work. I've also changed handling of institutional names (they should be in `{}` brackets). The escaping is in effect only in titles and subtitles, other fields shouldn't be problem.

**Comment by ghost** [comment]
great! thanks!
