### ISSUE TITLE
unicode-support for author-names?

### ISSUE THREAD

**Issue by ghost** [michal-h21/ctanbib#4]
Recently I get the error, that if a name contains certain letters (e.g. `ó`) the scripts aborts suddenly.
This leads to entries like this (receiving information for `babel` and next `dtxtut`).

```
@manual{babel,
title = {The Babel package},
subtitle = {Multilingual support for Plain TeX or LaTeX},
author = {Bezos L@manual{dtxtut,
title = {The Dtxtut package},
subtitle = {Tutorial on writing .dtx and .ins files},
author = {Pakin, Scott},
url = {http://www.ctan.org/pkg/dtxtut},
urldate = {2018-10-27}, 
date = {2015-09-13},
version = {2.1}
}
```

or

```
@manual{dirtree,
title = {The Dirtree package},
subtitle = {Display trees in the style of windows explorer},
author = {Charpentier, Jean-C@manual{graphicx,
title = {The Graphicx package},
subtitle = {Enhanced support for graphics},
author = {The LaTeX Team and Carlisle, David},
url = {http://www.ctan.org/pkg/graphicx},
urldate = {2018-10-27}, 
date = {2017-06-01},
version = {1.1a}
}
```

or

```
@manual{markdown,
title = {The Markdown package},
subtitle = {A package for converting and rendering markdown documents inside TeX},
author = {Novotn

```

**Comment by michal-h21** [comment]
That's strange. What OS do you use? It works for me on Linux.

**Comment by ghost** [comment]
macOS

**Comment by michal-h21** [comment]
Does the following code print correctly when you execute it with `texlua`?:
`
print "nazdar světe"`

**Comment by ghost** [comment]
```
nazdar světe
```

thats the result, so actually not a problem?!

The issue above does not happen all the time, sometimes it works.

I have it wrapped in a Makefile (but that shouldnt be the problem):

```
PKG   := hyperref widows-and-orphans tcolorbox geometry fontspec nowidow datatool biblatex archaeologie etoolbox babel dtxtut endnotes csquotes multicol listings microtype libertine enumitem xkeyval fontawesome ltxdoc xcolor dirtree graphicx cleveref returntogrid doc ctanbib marginnote markdown
CTAN  := ctanbib $$pkg | iconv >> $(CTANBIB) && echo "... $$pkg"


getCTAN:
ifneq ("$(wildcard $(CTANBIB))","")
	@echo -e "$(NAMEtypeout)\n$(RED)Skipping$(NC) retrieving information from CTAN.\n⁠\
	Using existing $(CTANBIB)\n\n";
else
	@echo -e "$(NAMEtypeout)\n$(RED)Retrieving$(NC) information from CTAN.\n⁠\
		Fetching information from CTAN about package..."
	for pkg in $(PKG);\
	do                \
	$(CTAN);          \
	done
endif
```

**Comment by ghost** [comment]
see edited answer above.

**Comment by michal-h21** [comment]
Yes, the result is correct. Looking at the Makefile, one suspicious thing is the `iconv` command, doesn't it cut the output at the non-ascii characters?

**Comment by ghost** [comment]
that describes exactly what happens, entries are cutted midway/when a non-ascii character shows up. Any suggestion I could use instead of `iconv`?

**Comment by michal-h21** [comment]
Just `ctanbib $$pkg >> $(CTANBIB)` should work, I think.

**Comment by ghost** [comment]
ok, that works, but now I get each entry twice. (I am sorry, this is certainly not related to your script but any suggestion would help me)

**Comment by ghost** [comment]
got it:

`CTAN  = ctanbib $$pkg >> $(CTANBIB) && echo "... $$pkg"` 
(removing `:` from `:=`).

thanks again, I will close this now.
