### ISSUE TITLE
The documentation should stipulate wget is required

### ISSUE THREAD

**Issue by dbitouze** [michal-h21/ctanbib#6]
The documentation should list the required software(s) for `ctanbib`: as reported on our [French TeX StackExchange clone](https://texnique.fr/osqa/questions/6532/comment-utiliser-le-script-ctanbib), a Windows user was stuck because of the lack of `wget`.

**Comment by michal-h21** [comment]
Thank's for the report, I've updated the documentation.

**Comment by dbitouze** [comment]
>Thank's for the report,

You're welcome!

> I've updated the documentation.

Nice, thanks. This led to another issue (#7).
