### ISSUE TITLE
curl in addition to wget?

### ISSUE THREAD

**Issue by dbitouze** [michal-h21/ctanbib#7]
Currently, `ctanbib` requires `wget` to work (#6).

What about `curl` in addition to (or instead of) `wget`? The former:
- is easy to install on Linux (if not shipped by default),
- is easy to install on Mac OS (AFAICS),
- [is shipped on Windows 10](https://devblogs.microsoft.com/commandline/tar-and-curl-come-to-windows/).

**Comment by michal-h21** [comment]
Sure, that seems like a good idea. It should work now.

**Comment by dbitouze** [comment]
Thanks!
