### ISSUE TITLE
Author missing

### ISSUE THREAD

**Issue by lhumb** [michal-h21/ctanbib#8]
When executing
 ctanbib pgf

I get: 
@manual{pgf,
title = {The Pgf package},
subtitle = {Create PostScript and PDF graphics in TeX},
author = { and  and },
url = {http://www.ctan.org/pkg/pgf},
urldate = {2019-09-14}, 
date = {2019-08-03},
version = {3.1.4b}
}

As you see, there are no authors… same with other packages …

**Comment by michal-h21** [comment]
It seems that the CTAN API changed and it doesn't contain the full author info by default. It can be requested using special parameter, but it doesn't work at the moment. CTAN maintainers know about this issue and they are working on a fix. It should start to work again soon, I hope.

**Comment by michal-h21** [comment]
I've added fix for this issue. The execution of ctanbib is bit slower, because it needs to retrieve and parse a big XML with full list of authors. It should continue to use the author info in the package info when it is available again.

**Comment by lhumb** [comment]
Thank you very much – in the meantime your package has found its way to ctan 
Its really nice you corrected it!
