### ISSUE TITLE
Missing curl under Windows 7/8.1

### ISSUE THREAD

**Issue by Roland-Brickl** [michal-h21/ctanbib#9]
Hello,

it would be nice, when there is some version of curl included in TexLive 2020. I downloaded the official version from https://curl.haxx.se/windows/ to get your ctanbib working.

What would be nice too: Make the package name optional in the case when there is only a --version or --help or even without any options.
There is always an error on the command line with that.

`C:\Users\Roland>ctanbib
ctanbib - convert ctan package information to bibtex format
Usage:
ctanbib [options] <package name>
Available options:
  -c,--ctan       Use @ctan type instead of @manual
  -h,--help       Print this message
  -v,--version    Print version info

C:\texlive\2019\bin\win32\runscript.tlu:911: command failed with exit code 1:
texlua c:\texlive\2019\texmf-dist\scripts\ctanbib\ctanbib`

`C:\Users\Roland>ctanbib -c
c:\texlive\2019\texmf-dist\scripts\ctanbib\ctanbib:38: attempt to concatenate a nil value (local 'pkgname')
C:\texlive\2019\bin\win32\runscript.tlu:911: command failed with exit code 1:
texlua c:\texlive\2019\texmf-dist\scripts\ctanbib\ctanbib -c`

`C:\Users\Roland>ctanbib -v
ctanbib version 0.1d
C:\texlive\2019\bin\win32\runscript.tlu:911: command failed with exit code 1:
texlua c:\texlive\2019\texmf-dist\scripts\ctanbib\ctanbib -v`

`C:\Users\Roland>ctanbib -h
ctanbib - convert ctan package information to bibtex format
Usage:
ctanbib [options] <package name>
Available options:
  -c,--ctan       Use @ctan type instead of @manual
  -h,--help       Print this message
  -v,--version    Print version info

C:\texlive\2019\bin\win32\runscript.tlu:911: command failed with exit code 1:
texlua c:\texlive\2019\texmf-dist\scripts\ctanbib\ctanbib -h`

Regards,
Roland

**Comment by michal-h21** [comment]
Hi Roland,

thank you for your suggestions. I've hopefully fixed the exit codes. I don't know why I used non-zero exit codes for correct invocation.

I don't think maintainers of TL would want to include CURL, as it is already included on most modern systems, and they generally don't like new binaries.

**Comment by Roland-Brickl** [comment]
Thanks Michal.

for the Texlive Installer there are 8 binarys for wget.
C:\texlive\2019\tlpkg\installer\wget
It's not on the PATH Environment under Windows.
It would maybe better to use wget2 or curl to benefit from the http2 protocol.

**Comment by koppor** [comment]
Tried today on MiKTeX on Windows 11; works well:

```cmd
$ ctanbib authorarchive                                           
@manual{authorarchive,                                            
title = {The authorarchive package},                              
subtitle = {Adds self-archiving information to scientific papers},
author = {Brucker, Achim D.},                                     
url = {https://ctan.org/pkg/authorarchive},                       
urldate = {2023-10-07},                                           
date = {2023-02-10},                                              
version = {1.3.0},                                                
}                                                                 
```

**Comment by michal-h21** [comment]
@koppor thanks for the report, I think we can close this now.
